name: emacs
version: '26.1'
summary: GNU Emacs, An extensible, customizable, free/libre text editor --- and more.
description: |
  Emacs snap, built out of GNU server. Classic confinement, so that the editor
  can access the filesystem outside $HOME.
grade: devel
confinement: classic

parts:
  emacs:
    plugin: autotools
    source: http://ftp.gnu.org/gnu/emacs/emacs-26.1.tar.gz
    build-packages:
      - libncurses5-dev
      - librsvg2-dev
      - libgif-dev
      - libtiff-dev
      - libpng-dev
      - libjpeg-dev
      - libm17n-dev
      - libotf-dev
      - imagemagick
      - libgtk-3-dev
      - libgnutls28-dev
      - libxml2-dev
      - libmagick++-6.q16-dev
      - libxpm-dev
      - libgpm-dev
      - libacl1-dev
      - libselinux1-dev
